# Generated by Django 3.0.6 on 2020-05-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edc_appointment', '0014_auto_20180116_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalappointment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical appointment'},
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site'),
        ),
    ]
